name: Claude Code Review

on:
  workflow_call:
    inputs:
      model:
        description: 'Claude model to use'
        required: false
        type: string
        default: 'claude-sonnet-4-5-20250929'
      prompt:
        description: 'Custom review prompt for Claude'
        required: false
        type: string
        default: |
          REPO: ${{ github.repository }}
          PR NUMBER: ${{ github.event.pull_request.number }}

          Perform a comprehensive code review with the following focus areas:

          1. **Code Quality**
             - Clean code principles and best practices
             - Proper error handling and edge cases
             - Code readability and maintainability

          2. **Security**
             - Check for potential security vulnerabilities
             - Validate input sanitization
             - Review authentication/authorization logic

          3. **Performance**
             - Identify potential performance bottlenecks
             - Review database queries for efficiency
             - Check for memory leaks or resource issues

          4. **Testing**
             - Verify adequate test coverage
             - Review test quality and edge cases
             - Check for missing test scenarios

          5. **Documentation**
             - Ensure code is properly documented
             - Verify README updates for new features
             - Check API documentation accuracy
          
          6. **Learning**
            - Based on the code review, provide a list of learning points for the developer based on the book "The Pragmatic Programmer".

          Provide detailed feedback using inline comments for specific issues.
          Use top-level comments for general observations or praise.
      use_sticky_comment:
        description: 'Use sticky comments to reuse the same comment on subsequent pushes'
        required: false
        type: boolean
        default: true
      track_progress:
        description: 'Enable progress tracking with checkboxes for comprehensive reviews'
        required: false
        type: boolean
        default: true
      allowed_tools:
        description: 'Comma-separated list of allowed tools for Claude'
        required: false
        type: string
      file_paths:
        description: 'File paths to restrict review to (JSON array as string)'
        required: false
        type: string
      skip_condition:
        description: 'Condition to skip review (e.g., contains title WIP)'
        required: false
        type: string
    secrets:
      ANTHROPIC_API_KEY:
        description: 'Anthropic API key for Claude Code'
        required: true
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-review:
    if: |
      github.event_name == 'workflow_call' || (
        github.event_name == 'pull_request' && (
          inputs.skip_condition == '' || !contains(github.event.pull_request.title, inputs.skip_condition)
        )
      )
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Sanitize inputs
        id: sanitize
        run: |
          # Sanitize allowed_tools by escaping shell special characters
          sanitized_tools="${{ inputs.allowed_tools }}"
          sanitized_tools="${sanitized_tools//\\/\\\\}"
          sanitized_tools="${sanitized_tools//\"/\\\"}"
          sanitized_tools="${sanitized_tools//$/\\$}"
          sanitized_tools="${sanitized_tools//\`/\\\`}"
          echo "allowed_tools=${sanitized_tools}" >> $GITHUB_OUTPUT

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1.0.8
        with:
          claude_code_oauth_token: ${{ secrets.ANTHROPIC_API_KEY }}
          
          # Use input parameters or defaults
          prompt: ${{ inputs.prompt }}
          use_sticky_comment: ${{ inputs.use_sticky_comment }}
          track_progress: ${{ inputs.track_progress }}
          claude_args: |
            --model ${{ inputs.model || 'claude-sonnet-4-5-20250929' }}
            --allowed-tools "${{ steps.sanitize.outputs.allowed_tools != '' && steps.sanitize.outputs.allowed_tools || 'mcp__github_inline_comment__create_inline_comment,Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*)' }}"