name: Claude Code Review
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    uses: ColoredCow/engineering-recipes/blob/main/.github/claude-code-review.yml@main
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
