name: Claude Code Review
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    permissions:
      actions: read
      contents: read
      issues: write
      pull-requests: write
      id-token: write
    uses: ColoredCow/engineering-recipes/.github/workflows/claude-code-review.yml@main
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
